version = 1

test_patterns = [
  "tests.py",
  "tests/**",
  "test_*.py"
]

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "python"
enabled = true
dependency_file_paths = [
  "requirements.txt",
  "Pipfile"
]

  [analyzers.meta]
  runtime_version = "3.x.x"
